package com.kyx.service.biz.controller.admin.todo.vo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Schema(description = "Admin - Todo Response VO")
@Data
public class TodoRespVO {

    @Schema(description = "Todo ID", requiredMode = Schema.RequiredMode.REQUIRED, example = "1024")
    private Long id;

    @Schema(description = "Title", requiredMode = Schema.RequiredMode.REQUIRED, example = "Monthly budget review")
    private String title;

    @Schema(description = "Description", example = "Notes and action items")
    private String description;

    @Schema(description = "Due date", example = "2025-01-30")
    private Date dueDate;

    @Schema(description = "Priority", example = "2")
    private Integer priority;

    @Schema(description = "Tags", example = "[\"approval\",\"hr\"]")
    private List<String> tags;

    @Schema(description = "Generated by business source", example = "true")
    private Boolean generatedFlag;

    @Schema(description = "Related business type", example = "WORK_REQUIREMENT")
    private String businessType;

    @Schema(description = "Related business ID", example = "1024")
    private Long businessId;

    @Schema(description = "Related task type", example = "DEVELOP")
    private String taskType;

    @Schema(description = "Route path", example = "/work/requirement/detail?id=1024")
    private String routePath;

    @Schema(description = "Status", example = "0")
    private Integer status;

    @Schema(description = "Created time", example = "2025-01-20 09:30:00")
    private Date createTime;

}
