-- ----------------------------
-- Table structure for hr_dingtalk_sync_snapshot
-- ----------------------------
CREATE TABLE IF NOT EXISTS `hr_dingtalk_sync_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `snapshot_batch_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Sync batch id',
  `snapshot_key` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Unique row key inside a batch',
  `sync_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EMPLOYEE_SYNC' COMMENT 'Sync type',
  `target_tenant_id` bigint DEFAULT NULL COMMENT 'Target tenant id',
  `action` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Sync action that caused the snapshot',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Snapshot reason',
  `profile_id` bigint DEFAULT NULL COMMENT 'HR employee profile id',
  `user_id` bigint DEFAULT NULL COMMENT 'System user id',
  `entry_id` bigint DEFAULT NULL COMMENT 'Employee entry id',
  `binding_id` bigint DEFAULT NULL COMMENT 'DingTalk binding id',
  `profile_snapshot` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether profile columns were captured',
  `entry_snapshot` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether entry columns were captured',
  `admin_user_snapshot` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether admin user columns were captured',
  `binding_snapshot` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether binding columns were captured',
  `before_profile_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Profile name before sync',
  `before_profile_mobile` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Profile mobile before sync',
  `before_profile_email` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Profile email before sync',
  `before_profile_status` tinyint DEFAULT NULL COMMENT 'Profile status before sync',
  `before_entry_work_status` tinyint DEFAULT NULL COMMENT 'Entry work status before sync',
  `before_entry_dept_id` bigint DEFAULT NULL COMMENT 'Entry dept id before sync',
  `before_entry_leave_date` date DEFAULT NULL COMMENT 'Entry leave date before sync',
  `before_entry_leave_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entry leave reason before sync',
  `before_admin_user_status` tinyint DEFAULT NULL COMMENT 'Admin user status before sync',
  `before_admin_user_dept_id` bigint DEFAULT NULL COMMENT 'Admin user dept id before sync',
  `before_ding_active` bit(1) DEFAULT NULL COMMENT 'DingTalk binding active flag before sync',
  `detail_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Additional before-image context',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted flag',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT 'Tenant id',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_hr_dingtalk_sync_snapshot_batch_key` (`tenant_id`,`snapshot_batch_id`,`snapshot_key`,`deleted`) USING BTREE,
  KEY `idx_hr_dingtalk_sync_snapshot_batch` (`tenant_id`,`snapshot_batch_id`,`create_time`) USING BTREE,
  KEY `idx_hr_dingtalk_sync_snapshot_profile` (`tenant_id`,`profile_id`) USING BTREE,
  KEY `idx_hr_dingtalk_sync_snapshot_user` (`tenant_id`,`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DingTalk employee sync before-image snapshots';
